import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";
import spacingPlugin from "./eslint-rules/no-unapproved-spacing.js";

export default tseslint.config(
  {
    ignores: [
      "dist",
      ".output",
      ".vinxi",
      ".nitro",
      ".tanstack",
      ".wrangler",
      // Generated by `prisma contract emit` / `prisma migration plan`; never edited by hand.
      "deploy/prisma/contract.d.ts",
      "deploy/prisma/migrations/**",
      "deploy/prisma/node_modules",
      "deploy/prisma/.prisma-composer",
      // Personal, git-excluded dev config.
      "vite.config.local.ts",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
      spacing: spacingPlugin,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "spacing/no-unapproved-spacing": "error",
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
          ],
        },
      ],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    // shadcn/ui primitives keep their upstream spacing (1.5, 2.5, ...); the 8px
    // scale applies to the site's own components.
    files: ["src/components/ui/**/*.{ts,tsx}"],
    rules: { "spacing/no-unapproved-spacing": "off" },
  },
  eslintPluginPrettier,
);
